/**
 * World of Crypto — global realm registry.
 *
 * 124 sharded realms across 13 geographic regions. Players are
 * matched to the nearest low-latency realm by the gateway, or may pick one
 * manually from the launcher. Each realm runs an isolated simulation and
 * population, with cross-realm guilds and the global leaderboard federated on
 * top.
 */

const REALMS = [
  {
    "id": 1,
    "name": "Zarathor-01",
    "region": "us-east",
    "regionLabel": "Americas — US East",
    "flag": "🇺🇸",
    "timezone": "America/New_York",
    "type": "PvP",
    "ws": "wss://us-east-1.worldofcrypto.example/realm",
    "http": "https://us-east-1.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 2,
    "name": "Valyrium-01",
    "region": "us-east",
    "regionLabel": "Americas — US East",
    "flag": "🇺🇸",
    "timezone": "America/New_York",
    "type": "RP",
    "ws": "wss://us-east-2.worldofcrypto.example/realm",
    "http": "https://us-east-2.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 3,
    "name": "Ironhold-01",
    "region": "us-east",
    "regionLabel": "Americas — US East",
    "flag": "🇺🇸",
    "timezone": "America/New_York",
    "type": "RP-PvP",
    "ws": "wss://us-east-3.worldofcrypto.example/realm",
    "http": "https://us-east-3.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 4,
    "name": "Frostspire-01",
    "region": "us-east",
    "regionLabel": "Americas — US East",
    "flag": "🇺🇸",
    "timezone": "America/New_York",
    "type": "Hardcore",
    "ws": "wss://us-east-4.worldofcrypto.example/realm",
    "http": "https://us-east-4.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 5,
    "name": "Obsidian-01",
    "region": "us-east",
    "regionLabel": "Americas — US East",
    "flag": "🇺🇸",
    "timezone": "America/New_York",
    "type": "PvE",
    "ws": "wss://us-east-5.worldofcrypto.example/realm",
    "http": "https://us-east-5.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 6,
    "name": "Shadowfen-01",
    "region": "us-east",
    "regionLabel": "Americas — US East",
    "flag": "🇺🇸",
    "timezone": "America/New_York",
    "type": "PvP",
    "ws": "wss://us-east-6.worldofcrypto.example/realm",
    "http": "https://us-east-6.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 7,
    "name": "Abyssal-01",
    "region": "us-east",
    "regionLabel": "Americas — US East",
    "flag": "🇺🇸",
    "timezone": "America/New_York",
    "type": "RP",
    "ws": "wss://us-east-7.worldofcrypto.example/realm",
    "http": "https://us-east-7.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 8,
    "name": "Bloodstone-01",
    "region": "us-east",
    "regionLabel": "Americas — US East",
    "flag": "🇺🇸",
    "timezone": "America/New_York",
    "type": "RP-PvP",
    "ws": "wss://us-east-8.worldofcrypto.example/realm",
    "http": "https://us-east-8.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 9,
    "name": "Tempest-01",
    "region": "us-east",
    "regionLabel": "Americas — US East",
    "flag": "🇺🇸",
    "timezone": "America/New_York",
    "type": "Hardcore",
    "ws": "wss://us-east-9.worldofcrypto.example/realm",
    "http": "https://us-east-9.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 10,
    "name": "Eternal-01",
    "region": "us-east",
    "regionLabel": "Americas — US East",
    "flag": "🇺🇸",
    "timezone": "America/New_York",
    "type": "PvE",
    "ws": "wss://us-east-10.worldofcrypto.example/realm",
    "http": "https://us-east-10.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 11,
    "name": "Emberfall-01",
    "region": "us-west",
    "regionLabel": "Americas — US West",
    "flag": "🇺🇸",
    "timezone": "America/Los_Angeles",
    "type": "PvP",
    "ws": "wss://us-west-11.worldofcrypto.example/realm",
    "http": "https://us-west-11.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 12,
    "name": "Stormgarde-01",
    "region": "us-west",
    "regionLabel": "Americas — US West",
    "flag": "🇺🇸",
    "timezone": "America/Los_Angeles",
    "type": "RP",
    "ws": "wss://us-west-12.worldofcrypto.example/realm",
    "http": "https://us-west-12.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 13,
    "name": "Duskwood-01",
    "region": "us-west",
    "regionLabel": "Americas — US West",
    "flag": "🇺🇸",
    "timezone": "America/Los_Angeles",
    "type": "RP-PvP",
    "ws": "wss://us-west-13.worldofcrypto.example/realm",
    "http": "https://us-west-13.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 14,
    "name": "Grimwatch-01",
    "region": "us-west",
    "regionLabel": "Americas — US West",
    "flag": "🇺🇸",
    "timezone": "America/Los_Angeles",
    "type": "Hardcore",
    "ws": "wss://us-west-14.worldofcrypto.example/realm",
    "http": "https://us-west-14.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 15,
    "name": "Hollowmere-01",
    "region": "us-west",
    "regionLabel": "Americas — US West",
    "flag": "🇺🇸",
    "timezone": "America/Los_Angeles",
    "type": "PvE",
    "ws": "wss://us-west-15.worldofcrypto.example/realm",
    "http": "https://us-west-15.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 16,
    "name": "Ravenholt-01",
    "region": "us-west",
    "regionLabel": "Americas — US West",
    "flag": "🇺🇸",
    "timezone": "America/Los_Angeles",
    "type": "PvP",
    "ws": "wss://us-west-16.worldofcrypto.example/realm",
    "http": "https://us-west-16.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 17,
    "name": "Thornvale-01",
    "region": "us-west",
    "regionLabel": "Americas — US West",
    "flag": "🇺🇸",
    "timezone": "America/Los_Angeles",
    "type": "RP",
    "ws": "wss://us-west-17.worldofcrypto.example/realm",
    "http": "https://us-west-17.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 18,
    "name": "Wyrmrest-01",
    "region": "us-west",
    "regionLabel": "Americas — US West",
    "flag": "🇺🇸",
    "timezone": "America/Los_Angeles",
    "type": "RP-PvP",
    "ws": "wss://us-west-18.worldofcrypto.example/realm",
    "http": "https://us-west-18.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 19,
    "name": "Ashenvale-01",
    "region": "us-west",
    "regionLabel": "Americas — US West",
    "flag": "🇺🇸",
    "timezone": "America/Los_Angeles",
    "type": "Hardcore",
    "ws": "wss://us-west-19.worldofcrypto.example/realm",
    "http": "https://us-west-19.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 20,
    "name": "Drakemoor-01",
    "region": "us-west",
    "regionLabel": "Americas — US West",
    "flag": "🇺🇸",
    "timezone": "America/Los_Angeles",
    "type": "PvE",
    "ws": "wss://us-west-20.worldofcrypto.example/realm",
    "http": "https://us-west-20.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 21,
    "name": "Silvermoon-01",
    "region": "sa",
    "regionLabel": "South America — São Paulo",
    "flag": "🇧🇷",
    "timezone": "America/Sao_Paulo",
    "type": "PvP",
    "ws": "wss://sa-21.worldofcrypto.example/realm",
    "http": "https://sa-21.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 22,
    "name": "Nightshade-01",
    "region": "sa",
    "regionLabel": "South America — São Paulo",
    "flag": "🇧🇷",
    "timezone": "America/Sao_Paulo",
    "type": "RP",
    "ws": "wss://sa-22.worldofcrypto.example/realm",
    "http": "https://sa-22.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 23,
    "name": "Doomhammer-01",
    "region": "sa",
    "regionLabel": "South America — São Paulo",
    "flag": "🇧🇷",
    "timezone": "America/Sao_Paulo",
    "type": "RP-PvP",
    "ws": "wss://sa-23.worldofcrypto.example/realm",
    "http": "https://sa-23.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 24,
    "name": "Direhaven-01",
    "region": "sa",
    "regionLabel": "South America — São Paulo",
    "flag": "🇧🇷",
    "timezone": "America/Sao_Paulo",
    "type": "Hardcore",
    "ws": "wss://sa-24.worldofcrypto.example/realm",
    "http": "https://sa-24.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 25,
    "name": "Voidreach-01",
    "region": "sa",
    "regionLabel": "South America — São Paulo",
    "flag": "🇧🇷",
    "timezone": "America/Sao_Paulo",
    "type": "PvE",
    "ws": "wss://sa-25.worldofcrypto.example/realm",
    "http": "https://sa-25.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 26,
    "name": "Zarathor-02",
    "region": "sa",
    "regionLabel": "South America — São Paulo",
    "flag": "🇧🇷",
    "timezone": "America/Sao_Paulo",
    "type": "PvP",
    "ws": "wss://sa-26.worldofcrypto.example/realm",
    "http": "https://sa-26.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 27,
    "name": "Valyrium-02",
    "region": "sa",
    "regionLabel": "South America — São Paulo",
    "flag": "🇧🇷",
    "timezone": "America/Sao_Paulo",
    "type": "RP",
    "ws": "wss://sa-27.worldofcrypto.example/realm",
    "http": "https://sa-27.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 28,
    "name": "Ironhold-02",
    "region": "sa",
    "regionLabel": "South America — São Paulo",
    "flag": "🇧🇷",
    "timezone": "America/Sao_Paulo",
    "type": "RP-PvP",
    "ws": "wss://sa-28.worldofcrypto.example/realm",
    "http": "https://sa-28.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 29,
    "name": "Frostspire-02",
    "region": "sa",
    "regionLabel": "South America — São Paulo",
    "flag": "🇧🇷",
    "timezone": "America/Sao_Paulo",
    "type": "Hardcore",
    "ws": "wss://sa-29.worldofcrypto.example/realm",
    "http": "https://sa-29.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 30,
    "name": "Obsidian-02",
    "region": "sa",
    "regionLabel": "South America — São Paulo",
    "flag": "🇧🇷",
    "timezone": "America/Sao_Paulo",
    "type": "PvE",
    "ws": "wss://sa-30.worldofcrypto.example/realm",
    "http": "https://sa-30.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 31,
    "name": "Shadowfen-02",
    "region": "eu-central",
    "regionLabel": "Europe — Central",
    "flag": "🇪🇺",
    "timezone": "Europe/Frankfurt",
    "type": "PvP",
    "ws": "wss://eu-central-31.worldofcrypto.example/realm",
    "http": "https://eu-central-31.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 32,
    "name": "Abyssal-02",
    "region": "eu-central",
    "regionLabel": "Europe — Central",
    "flag": "🇪🇺",
    "timezone": "Europe/Frankfurt",
    "type": "RP",
    "ws": "wss://eu-central-32.worldofcrypto.example/realm",
    "http": "https://eu-central-32.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 33,
    "name": "Bloodstone-02",
    "region": "eu-central",
    "regionLabel": "Europe — Central",
    "flag": "🇪🇺",
    "timezone": "Europe/Frankfurt",
    "type": "RP-PvP",
    "ws": "wss://eu-central-33.worldofcrypto.example/realm",
    "http": "https://eu-central-33.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 34,
    "name": "Tempest-02",
    "region": "eu-central",
    "regionLabel": "Europe — Central",
    "flag": "🇪🇺",
    "timezone": "Europe/Frankfurt",
    "type": "Hardcore",
    "ws": "wss://eu-central-34.worldofcrypto.example/realm",
    "http": "https://eu-central-34.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 35,
    "name": "Eternal-02",
    "region": "eu-central",
    "regionLabel": "Europe — Central",
    "flag": "🇪🇺",
    "timezone": "Europe/Frankfurt",
    "type": "PvE",
    "ws": "wss://eu-central-35.worldofcrypto.example/realm",
    "http": "https://eu-central-35.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 36,
    "name": "Emberfall-02",
    "region": "eu-central",
    "regionLabel": "Europe — Central",
    "flag": "🇪🇺",
    "timezone": "Europe/Frankfurt",
    "type": "PvP",
    "ws": "wss://eu-central-36.worldofcrypto.example/realm",
    "http": "https://eu-central-36.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 37,
    "name": "Stormgarde-02",
    "region": "eu-central",
    "regionLabel": "Europe — Central",
    "flag": "🇪🇺",
    "timezone": "Europe/Frankfurt",
    "type": "RP",
    "ws": "wss://eu-central-37.worldofcrypto.example/realm",
    "http": "https://eu-central-37.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 38,
    "name": "Duskwood-02",
    "region": "eu-central",
    "regionLabel": "Europe — Central",
    "flag": "🇪🇺",
    "timezone": "Europe/Frankfurt",
    "type": "RP-PvP",
    "ws": "wss://eu-central-38.worldofcrypto.example/realm",
    "http": "https://eu-central-38.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 39,
    "name": "Grimwatch-02",
    "region": "eu-central",
    "regionLabel": "Europe — Central",
    "flag": "🇪🇺",
    "timezone": "Europe/Frankfurt",
    "type": "Hardcore",
    "ws": "wss://eu-central-39.worldofcrypto.example/realm",
    "http": "https://eu-central-39.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 40,
    "name": "Hollowmere-02",
    "region": "eu-central",
    "regionLabel": "Europe — Central",
    "flag": "🇪🇺",
    "timezone": "Europe/Frankfurt",
    "type": "PvE",
    "ws": "wss://eu-central-40.worldofcrypto.example/realm",
    "http": "https://eu-central-40.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 41,
    "name": "Ravenholt-02",
    "region": "eu-west",
    "regionLabel": "Europe — West",
    "flag": "🇬🇧",
    "timezone": "Europe/London",
    "type": "PvP",
    "ws": "wss://eu-west-41.worldofcrypto.example/realm",
    "http": "https://eu-west-41.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 42,
    "name": "Thornvale-02",
    "region": "eu-west",
    "regionLabel": "Europe — West",
    "flag": "🇬🇧",
    "timezone": "Europe/London",
    "type": "RP",
    "ws": "wss://eu-west-42.worldofcrypto.example/realm",
    "http": "https://eu-west-42.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 43,
    "name": "Wyrmrest-02",
    "region": "eu-west",
    "regionLabel": "Europe — West",
    "flag": "🇬🇧",
    "timezone": "Europe/London",
    "type": "RP-PvP",
    "ws": "wss://eu-west-43.worldofcrypto.example/realm",
    "http": "https://eu-west-43.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 44,
    "name": "Ashenvale-02",
    "region": "eu-west",
    "regionLabel": "Europe — West",
    "flag": "🇬🇧",
    "timezone": "Europe/London",
    "type": "Hardcore",
    "ws": "wss://eu-west-44.worldofcrypto.example/realm",
    "http": "https://eu-west-44.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 45,
    "name": "Drakemoor-02",
    "region": "eu-west",
    "regionLabel": "Europe — West",
    "flag": "🇬🇧",
    "timezone": "Europe/London",
    "type": "PvE",
    "ws": "wss://eu-west-45.worldofcrypto.example/realm",
    "http": "https://eu-west-45.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 46,
    "name": "Silvermoon-02",
    "region": "eu-west",
    "regionLabel": "Europe — West",
    "flag": "🇬🇧",
    "timezone": "Europe/London",
    "type": "PvP",
    "ws": "wss://eu-west-46.worldofcrypto.example/realm",
    "http": "https://eu-west-46.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 47,
    "name": "Nightshade-02",
    "region": "eu-west",
    "regionLabel": "Europe — West",
    "flag": "🇬🇧",
    "timezone": "Europe/London",
    "type": "RP",
    "ws": "wss://eu-west-47.worldofcrypto.example/realm",
    "http": "https://eu-west-47.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 48,
    "name": "Doomhammer-02",
    "region": "eu-west",
    "regionLabel": "Europe — West",
    "flag": "🇬🇧",
    "timezone": "Europe/London",
    "type": "RP-PvP",
    "ws": "wss://eu-west-48.worldofcrypto.example/realm",
    "http": "https://eu-west-48.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 49,
    "name": "Direhaven-02",
    "region": "eu-west",
    "regionLabel": "Europe — West",
    "flag": "🇬🇧",
    "timezone": "Europe/London",
    "type": "Hardcore",
    "ws": "wss://eu-west-49.worldofcrypto.example/realm",
    "http": "https://eu-west-49.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 50,
    "name": "Voidreach-02",
    "region": "eu-west",
    "regionLabel": "Europe — West",
    "flag": "🇬🇧",
    "timezone": "Europe/London",
    "type": "PvE",
    "ws": "wss://eu-west-50.worldofcrypto.example/realm",
    "http": "https://eu-west-50.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 51,
    "name": "Zarathor-03",
    "region": "eu-nordic",
    "regionLabel": "Europe — Nordic",
    "flag": "🇸🇪",
    "timezone": "Europe/Stockholm",
    "type": "PvP",
    "ws": "wss://eu-nordic-51.worldofcrypto.example/realm",
    "http": "https://eu-nordic-51.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 52,
    "name": "Valyrium-03",
    "region": "eu-nordic",
    "regionLabel": "Europe — Nordic",
    "flag": "🇸🇪",
    "timezone": "Europe/Stockholm",
    "type": "RP",
    "ws": "wss://eu-nordic-52.worldofcrypto.example/realm",
    "http": "https://eu-nordic-52.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 53,
    "name": "Ironhold-03",
    "region": "eu-nordic",
    "regionLabel": "Europe — Nordic",
    "flag": "🇸🇪",
    "timezone": "Europe/Stockholm",
    "type": "RP-PvP",
    "ws": "wss://eu-nordic-53.worldofcrypto.example/realm",
    "http": "https://eu-nordic-53.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 54,
    "name": "Frostspire-03",
    "region": "eu-nordic",
    "regionLabel": "Europe — Nordic",
    "flag": "🇸🇪",
    "timezone": "Europe/Stockholm",
    "type": "Hardcore",
    "ws": "wss://eu-nordic-54.worldofcrypto.example/realm",
    "http": "https://eu-nordic-54.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 55,
    "name": "Obsidian-03",
    "region": "eu-nordic",
    "regionLabel": "Europe — Nordic",
    "flag": "🇸🇪",
    "timezone": "Europe/Stockholm",
    "type": "PvE",
    "ws": "wss://eu-nordic-55.worldofcrypto.example/realm",
    "http": "https://eu-nordic-55.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 56,
    "name": "Shadowfen-03",
    "region": "eu-nordic",
    "regionLabel": "Europe — Nordic",
    "flag": "🇸🇪",
    "timezone": "Europe/Stockholm",
    "type": "PvP",
    "ws": "wss://eu-nordic-56.worldofcrypto.example/realm",
    "http": "https://eu-nordic-56.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 57,
    "name": "Abyssal-03",
    "region": "eu-nordic",
    "regionLabel": "Europe — Nordic",
    "flag": "🇸🇪",
    "timezone": "Europe/Stockholm",
    "type": "RP",
    "ws": "wss://eu-nordic-57.worldofcrypto.example/realm",
    "http": "https://eu-nordic-57.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 58,
    "name": "Bloodstone-03",
    "region": "eu-nordic",
    "regionLabel": "Europe — Nordic",
    "flag": "🇸🇪",
    "timezone": "Europe/Stockholm",
    "type": "RP-PvP",
    "ws": "wss://eu-nordic-58.worldofcrypto.example/realm",
    "http": "https://eu-nordic-58.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 59,
    "name": "Tempest-03",
    "region": "eu-nordic",
    "regionLabel": "Europe — Nordic",
    "flag": "🇸🇪",
    "timezone": "Europe/Stockholm",
    "type": "Hardcore",
    "ws": "wss://eu-nordic-59.worldofcrypto.example/realm",
    "http": "https://eu-nordic-59.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 60,
    "name": "Eternal-03",
    "region": "eu-nordic",
    "regionLabel": "Europe — Nordic",
    "flag": "🇸🇪",
    "timezone": "Europe/Stockholm",
    "type": "PvE",
    "ws": "wss://eu-nordic-60.worldofcrypto.example/realm",
    "http": "https://eu-nordic-60.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 61,
    "name": "Emberfall-03",
    "region": "me",
    "regionLabel": "Middle East — Dubai",
    "flag": "🇦🇪",
    "timezone": "Asia/Dubai",
    "type": "PvP",
    "ws": "wss://me-61.worldofcrypto.example/realm",
    "http": "https://me-61.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 62,
    "name": "Stormgarde-03",
    "region": "me",
    "regionLabel": "Middle East — Dubai",
    "flag": "🇦🇪",
    "timezone": "Asia/Dubai",
    "type": "RP",
    "ws": "wss://me-62.worldofcrypto.example/realm",
    "http": "https://me-62.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 63,
    "name": "Duskwood-03",
    "region": "me",
    "regionLabel": "Middle East — Dubai",
    "flag": "🇦🇪",
    "timezone": "Asia/Dubai",
    "type": "RP-PvP",
    "ws": "wss://me-63.worldofcrypto.example/realm",
    "http": "https://me-63.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 64,
    "name": "Grimwatch-03",
    "region": "me",
    "regionLabel": "Middle East — Dubai",
    "flag": "🇦🇪",
    "timezone": "Asia/Dubai",
    "type": "Hardcore",
    "ws": "wss://me-64.worldofcrypto.example/realm",
    "http": "https://me-64.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 65,
    "name": "Hollowmere-03",
    "region": "me",
    "regionLabel": "Middle East — Dubai",
    "flag": "🇦🇪",
    "timezone": "Asia/Dubai",
    "type": "PvE",
    "ws": "wss://me-65.worldofcrypto.example/realm",
    "http": "https://me-65.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 66,
    "name": "Ravenholt-03",
    "region": "me",
    "regionLabel": "Middle East — Dubai",
    "flag": "🇦🇪",
    "timezone": "Asia/Dubai",
    "type": "PvP",
    "ws": "wss://me-66.worldofcrypto.example/realm",
    "http": "https://me-66.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 67,
    "name": "Thornvale-03",
    "region": "me",
    "regionLabel": "Middle East — Dubai",
    "flag": "🇦🇪",
    "timezone": "Asia/Dubai",
    "type": "RP",
    "ws": "wss://me-67.worldofcrypto.example/realm",
    "http": "https://me-67.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 68,
    "name": "Wyrmrest-03",
    "region": "me",
    "regionLabel": "Middle East — Dubai",
    "flag": "🇦🇪",
    "timezone": "Asia/Dubai",
    "type": "RP-PvP",
    "ws": "wss://me-68.worldofcrypto.example/realm",
    "http": "https://me-68.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 69,
    "name": "Ashenvale-03",
    "region": "me",
    "regionLabel": "Middle East — Dubai",
    "flag": "🇦🇪",
    "timezone": "Asia/Dubai",
    "type": "Hardcore",
    "ws": "wss://me-69.worldofcrypto.example/realm",
    "http": "https://me-69.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 70,
    "name": "Drakemoor-03",
    "region": "me",
    "regionLabel": "Middle East — Dubai",
    "flag": "🇦🇪",
    "timezone": "Asia/Dubai",
    "type": "PvE",
    "ws": "wss://me-70.worldofcrypto.example/realm",
    "http": "https://me-70.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 71,
    "name": "Silvermoon-03",
    "region": "ap-south",
    "regionLabel": "Asia Pacific — Mumbai",
    "flag": "🇮🇳",
    "timezone": "Asia/Kolkata",
    "type": "PvP",
    "ws": "wss://ap-south-71.worldofcrypto.example/realm",
    "http": "https://ap-south-71.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 72,
    "name": "Nightshade-03",
    "region": "ap-south",
    "regionLabel": "Asia Pacific — Mumbai",
    "flag": "🇮🇳",
    "timezone": "Asia/Kolkata",
    "type": "RP",
    "ws": "wss://ap-south-72.worldofcrypto.example/realm",
    "http": "https://ap-south-72.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 73,
    "name": "Doomhammer-03",
    "region": "ap-south",
    "regionLabel": "Asia Pacific — Mumbai",
    "flag": "🇮🇳",
    "timezone": "Asia/Kolkata",
    "type": "RP-PvP",
    "ws": "wss://ap-south-73.worldofcrypto.example/realm",
    "http": "https://ap-south-73.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 74,
    "name": "Direhaven-03",
    "region": "ap-south",
    "regionLabel": "Asia Pacific — Mumbai",
    "flag": "🇮🇳",
    "timezone": "Asia/Kolkata",
    "type": "Hardcore",
    "ws": "wss://ap-south-74.worldofcrypto.example/realm",
    "http": "https://ap-south-74.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 75,
    "name": "Voidreach-03",
    "region": "ap-south",
    "regionLabel": "Asia Pacific — Mumbai",
    "flag": "🇮🇳",
    "timezone": "Asia/Kolkata",
    "type": "PvE",
    "ws": "wss://ap-south-75.worldofcrypto.example/realm",
    "http": "https://ap-south-75.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 76,
    "name": "Zarathor-04",
    "region": "ap-south",
    "regionLabel": "Asia Pacific — Mumbai",
    "flag": "🇮🇳",
    "timezone": "Asia/Kolkata",
    "type": "PvP",
    "ws": "wss://ap-south-76.worldofcrypto.example/realm",
    "http": "https://ap-south-76.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 77,
    "name": "Valyrium-04",
    "region": "ap-south",
    "regionLabel": "Asia Pacific — Mumbai",
    "flag": "🇮🇳",
    "timezone": "Asia/Kolkata",
    "type": "RP",
    "ws": "wss://ap-south-77.worldofcrypto.example/realm",
    "http": "https://ap-south-77.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 78,
    "name": "Ironhold-04",
    "region": "ap-south",
    "regionLabel": "Asia Pacific — Mumbai",
    "flag": "🇮🇳",
    "timezone": "Asia/Kolkata",
    "type": "RP-PvP",
    "ws": "wss://ap-south-78.worldofcrypto.example/realm",
    "http": "https://ap-south-78.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 79,
    "name": "Frostspire-04",
    "region": "ap-south",
    "regionLabel": "Asia Pacific — Mumbai",
    "flag": "🇮🇳",
    "timezone": "Asia/Kolkata",
    "type": "Hardcore",
    "ws": "wss://ap-south-79.worldofcrypto.example/realm",
    "http": "https://ap-south-79.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 80,
    "name": "Obsidian-04",
    "region": "ap-south",
    "regionLabel": "Asia Pacific — Mumbai",
    "flag": "🇮🇳",
    "timezone": "Asia/Kolkata",
    "type": "PvE",
    "ws": "wss://ap-south-80.worldofcrypto.example/realm",
    "http": "https://ap-south-80.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 81,
    "name": "Shadowfen-04",
    "region": "ap-southeast",
    "regionLabel": "Asia Pacific — Singapore",
    "flag": "🇸🇬",
    "timezone": "Asia/Singapore",
    "type": "PvP",
    "ws": "wss://ap-southeast-81.worldofcrypto.example/realm",
    "http": "https://ap-southeast-81.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 82,
    "name": "Abyssal-04",
    "region": "ap-southeast",
    "regionLabel": "Asia Pacific — Singapore",
    "flag": "🇸🇬",
    "timezone": "Asia/Singapore",
    "type": "RP",
    "ws": "wss://ap-southeast-82.worldofcrypto.example/realm",
    "http": "https://ap-southeast-82.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 83,
    "name": "Bloodstone-04",
    "region": "ap-southeast",
    "regionLabel": "Asia Pacific — Singapore",
    "flag": "🇸🇬",
    "timezone": "Asia/Singapore",
    "type": "RP-PvP",
    "ws": "wss://ap-southeast-83.worldofcrypto.example/realm",
    "http": "https://ap-southeast-83.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 84,
    "name": "Tempest-04",
    "region": "ap-southeast",
    "regionLabel": "Asia Pacific — Singapore",
    "flag": "🇸🇬",
    "timezone": "Asia/Singapore",
    "type": "Hardcore",
    "ws": "wss://ap-southeast-84.worldofcrypto.example/realm",
    "http": "https://ap-southeast-84.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 85,
    "name": "Eternal-04",
    "region": "ap-southeast",
    "regionLabel": "Asia Pacific — Singapore",
    "flag": "🇸🇬",
    "timezone": "Asia/Singapore",
    "type": "PvE",
    "ws": "wss://ap-southeast-85.worldofcrypto.example/realm",
    "http": "https://ap-southeast-85.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 86,
    "name": "Emberfall-04",
    "region": "ap-southeast",
    "regionLabel": "Asia Pacific — Singapore",
    "flag": "🇸🇬",
    "timezone": "Asia/Singapore",
    "type": "PvP",
    "ws": "wss://ap-southeast-86.worldofcrypto.example/realm",
    "http": "https://ap-southeast-86.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 87,
    "name": "Stormgarde-04",
    "region": "ap-southeast",
    "regionLabel": "Asia Pacific — Singapore",
    "flag": "🇸🇬",
    "timezone": "Asia/Singapore",
    "type": "RP",
    "ws": "wss://ap-southeast-87.worldofcrypto.example/realm",
    "http": "https://ap-southeast-87.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 88,
    "name": "Duskwood-04",
    "region": "ap-southeast",
    "regionLabel": "Asia Pacific — Singapore",
    "flag": "🇸🇬",
    "timezone": "Asia/Singapore",
    "type": "RP-PvP",
    "ws": "wss://ap-southeast-88.worldofcrypto.example/realm",
    "http": "https://ap-southeast-88.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 89,
    "name": "Grimwatch-04",
    "region": "ap-southeast",
    "regionLabel": "Asia Pacific — Singapore",
    "flag": "🇸🇬",
    "timezone": "Asia/Singapore",
    "type": "Hardcore",
    "ws": "wss://ap-southeast-89.worldofcrypto.example/realm",
    "http": "https://ap-southeast-89.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 90,
    "name": "Hollowmere-04",
    "region": "ap-southeast",
    "regionLabel": "Asia Pacific — Singapore",
    "flag": "🇸🇬",
    "timezone": "Asia/Singapore",
    "type": "PvE",
    "ws": "wss://ap-southeast-90.worldofcrypto.example/realm",
    "http": "https://ap-southeast-90.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 91,
    "name": "Ravenholt-04",
    "region": "ap-northeast",
    "regionLabel": "Asia Pacific — Tokyo",
    "flag": "🇯🇵",
    "timezone": "Asia/Tokyo",
    "type": "PvP",
    "ws": "wss://ap-northeast-91.worldofcrypto.example/realm",
    "http": "https://ap-northeast-91.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 92,
    "name": "Thornvale-04",
    "region": "ap-northeast",
    "regionLabel": "Asia Pacific — Tokyo",
    "flag": "🇯🇵",
    "timezone": "Asia/Tokyo",
    "type": "RP",
    "ws": "wss://ap-northeast-92.worldofcrypto.example/realm",
    "http": "https://ap-northeast-92.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 93,
    "name": "Wyrmrest-04",
    "region": "ap-northeast",
    "regionLabel": "Asia Pacific — Tokyo",
    "flag": "🇯🇵",
    "timezone": "Asia/Tokyo",
    "type": "RP-PvP",
    "ws": "wss://ap-northeast-93.worldofcrypto.example/realm",
    "http": "https://ap-northeast-93.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 94,
    "name": "Ashenvale-04",
    "region": "ap-northeast",
    "regionLabel": "Asia Pacific — Tokyo",
    "flag": "🇯🇵",
    "timezone": "Asia/Tokyo",
    "type": "Hardcore",
    "ws": "wss://ap-northeast-94.worldofcrypto.example/realm",
    "http": "https://ap-northeast-94.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 95,
    "name": "Drakemoor-04",
    "region": "ap-northeast",
    "regionLabel": "Asia Pacific — Tokyo",
    "flag": "🇯🇵",
    "timezone": "Asia/Tokyo",
    "type": "PvE",
    "ws": "wss://ap-northeast-95.worldofcrypto.example/realm",
    "http": "https://ap-northeast-95.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 96,
    "name": "Silvermoon-04",
    "region": "ap-northeast",
    "regionLabel": "Asia Pacific — Tokyo",
    "flag": "🇯🇵",
    "timezone": "Asia/Tokyo",
    "type": "PvP",
    "ws": "wss://ap-northeast-96.worldofcrypto.example/realm",
    "http": "https://ap-northeast-96.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 97,
    "name": "Nightshade-04",
    "region": "ap-northeast",
    "regionLabel": "Asia Pacific — Tokyo",
    "flag": "🇯🇵",
    "timezone": "Asia/Tokyo",
    "type": "RP",
    "ws": "wss://ap-northeast-97.worldofcrypto.example/realm",
    "http": "https://ap-northeast-97.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 98,
    "name": "Doomhammer-04",
    "region": "ap-northeast",
    "regionLabel": "Asia Pacific — Tokyo",
    "flag": "🇯🇵",
    "timezone": "Asia/Tokyo",
    "type": "RP-PvP",
    "ws": "wss://ap-northeast-98.worldofcrypto.example/realm",
    "http": "https://ap-northeast-98.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 99,
    "name": "Direhaven-04",
    "region": "ap-northeast",
    "regionLabel": "Asia Pacific — Tokyo",
    "flag": "🇯🇵",
    "timezone": "Asia/Tokyo",
    "type": "Hardcore",
    "ws": "wss://ap-northeast-99.worldofcrypto.example/realm",
    "http": "https://ap-northeast-99.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 100,
    "name": "Voidreach-04",
    "region": "ap-northeast",
    "regionLabel": "Asia Pacific — Tokyo",
    "flag": "🇯🇵",
    "timezone": "Asia/Tokyo",
    "type": "PvE",
    "ws": "wss://ap-northeast-100.worldofcrypto.example/realm",
    "http": "https://ap-northeast-100.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 101,
    "name": "Zarathor-05",
    "region": "kr",
    "regionLabel": "Asia Pacific — Seoul",
    "flag": "🇰🇷",
    "timezone": "Asia/Seoul",
    "type": "PvP",
    "ws": "wss://kr-101.worldofcrypto.example/realm",
    "http": "https://kr-101.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 102,
    "name": "Valyrium-05",
    "region": "kr",
    "regionLabel": "Asia Pacific — Seoul",
    "flag": "🇰🇷",
    "timezone": "Asia/Seoul",
    "type": "RP",
    "ws": "wss://kr-102.worldofcrypto.example/realm",
    "http": "https://kr-102.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 103,
    "name": "Ironhold-05",
    "region": "kr",
    "regionLabel": "Asia Pacific — Seoul",
    "flag": "🇰🇷",
    "timezone": "Asia/Seoul",
    "type": "RP-PvP",
    "ws": "wss://kr-103.worldofcrypto.example/realm",
    "http": "https://kr-103.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 104,
    "name": "Frostspire-05",
    "region": "kr",
    "regionLabel": "Asia Pacific — Seoul",
    "flag": "🇰🇷",
    "timezone": "Asia/Seoul",
    "type": "Hardcore",
    "ws": "wss://kr-104.worldofcrypto.example/realm",
    "http": "https://kr-104.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 105,
    "name": "Obsidian-05",
    "region": "kr",
    "regionLabel": "Asia Pacific — Seoul",
    "flag": "🇰🇷",
    "timezone": "Asia/Seoul",
    "type": "PvE",
    "ws": "wss://kr-105.worldofcrypto.example/realm",
    "http": "https://kr-105.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 106,
    "name": "Shadowfen-05",
    "region": "kr",
    "regionLabel": "Asia Pacific — Seoul",
    "flag": "🇰🇷",
    "timezone": "Asia/Seoul",
    "type": "PvP",
    "ws": "wss://kr-106.worldofcrypto.example/realm",
    "http": "https://kr-106.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 107,
    "name": "Abyssal-05",
    "region": "kr",
    "regionLabel": "Asia Pacific — Seoul",
    "flag": "🇰🇷",
    "timezone": "Asia/Seoul",
    "type": "RP",
    "ws": "wss://kr-107.worldofcrypto.example/realm",
    "http": "https://kr-107.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 108,
    "name": "Bloodstone-05",
    "region": "kr",
    "regionLabel": "Asia Pacific — Seoul",
    "flag": "🇰🇷",
    "timezone": "Asia/Seoul",
    "type": "RP-PvP",
    "ws": "wss://kr-108.worldofcrypto.example/realm",
    "http": "https://kr-108.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 109,
    "name": "Tempest-05",
    "region": "kr",
    "regionLabel": "Asia Pacific — Seoul",
    "flag": "🇰🇷",
    "timezone": "Asia/Seoul",
    "type": "Hardcore",
    "ws": "wss://kr-109.worldofcrypto.example/realm",
    "http": "https://kr-109.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 110,
    "name": "Eternal-05",
    "region": "kr",
    "regionLabel": "Asia Pacific — Seoul",
    "flag": "🇰🇷",
    "timezone": "Asia/Seoul",
    "type": "PvE",
    "ws": "wss://kr-110.worldofcrypto.example/realm",
    "http": "https://kr-110.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 111,
    "name": "Emberfall-05",
    "region": "oce",
    "regionLabel": "Oceania — Sydney",
    "flag": "🇦🇺",
    "timezone": "Australia/Sydney",
    "type": "PvP",
    "ws": "wss://oce-111.worldofcrypto.example/realm",
    "http": "https://oce-111.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 112,
    "name": "Stormgarde-05",
    "region": "oce",
    "regionLabel": "Oceania — Sydney",
    "flag": "🇦🇺",
    "timezone": "Australia/Sydney",
    "type": "RP",
    "ws": "wss://oce-112.worldofcrypto.example/realm",
    "http": "https://oce-112.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 113,
    "name": "Duskwood-05",
    "region": "oce",
    "regionLabel": "Oceania — Sydney",
    "flag": "🇦🇺",
    "timezone": "Australia/Sydney",
    "type": "RP-PvP",
    "ws": "wss://oce-113.worldofcrypto.example/realm",
    "http": "https://oce-113.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 114,
    "name": "Grimwatch-05",
    "region": "oce",
    "regionLabel": "Oceania — Sydney",
    "flag": "🇦🇺",
    "timezone": "Australia/Sydney",
    "type": "Hardcore",
    "ws": "wss://oce-114.worldofcrypto.example/realm",
    "http": "https://oce-114.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 115,
    "name": "Hollowmere-05",
    "region": "oce",
    "regionLabel": "Oceania — Sydney",
    "flag": "🇦🇺",
    "timezone": "Australia/Sydney",
    "type": "PvE",
    "ws": "wss://oce-115.worldofcrypto.example/realm",
    "http": "https://oce-115.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 116,
    "name": "Ravenholt-05",
    "region": "oce",
    "regionLabel": "Oceania — Sydney",
    "flag": "🇦🇺",
    "timezone": "Australia/Sydney",
    "type": "PvP",
    "ws": "wss://oce-116.worldofcrypto.example/realm",
    "http": "https://oce-116.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 117,
    "name": "Thornvale-05",
    "region": "oce",
    "regionLabel": "Oceania — Sydney",
    "flag": "🇦🇺",
    "timezone": "Australia/Sydney",
    "type": "RP",
    "ws": "wss://oce-117.worldofcrypto.example/realm",
    "http": "https://oce-117.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 118,
    "name": "Wyrmrest-05",
    "region": "oce",
    "regionLabel": "Oceania — Sydney",
    "flag": "🇦🇺",
    "timezone": "Australia/Sydney",
    "type": "RP-PvP",
    "ws": "wss://oce-118.worldofcrypto.example/realm",
    "http": "https://oce-118.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 119,
    "name": "Ashenvale-05",
    "region": "oce",
    "regionLabel": "Oceania — Sydney",
    "flag": "🇦🇺",
    "timezone": "Australia/Sydney",
    "type": "Hardcore",
    "ws": "wss://oce-119.worldofcrypto.example/realm",
    "http": "https://oce-119.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  },
  {
    "id": 120,
    "name": "Drakemoor-05",
    "region": "oce",
    "regionLabel": "Oceania — Sydney",
    "flag": "🇦🇺",
    "timezone": "Australia/Sydney",
    "type": "PvE",
    "ws": "wss://oce-120.worldofcrypto.example/realm",
    "http": "https://oce-120.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 121,
    "name": "Silvermoon-05",
    "region": "af",
    "regionLabel": "Africa — Johannesburg",
    "flag": "🇿🇦",
    "timezone": "Africa/Johannesburg",
    "type": "PvP",
    "ws": "wss://af-121.worldofcrypto.example/realm",
    "http": "https://af-121.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 122,
    "name": "Nightshade-05",
    "region": "af",
    "regionLabel": "Africa — Johannesburg",
    "flag": "🇿🇦",
    "timezone": "Africa/Johannesburg",
    "type": "RP",
    "ws": "wss://af-122.worldofcrypto.example/realm",
    "http": "https://af-122.worldofcrypto.example",
    "capacity": 2000,
    "status": "online"
  },
  {
    "id": 123,
    "name": "Doomhammer-05",
    "region": "af",
    "regionLabel": "Africa — Johannesburg",
    "flag": "🇿🇦",
    "timezone": "Africa/Johannesburg",
    "type": "RP-PvP",
    "ws": "wss://af-123.worldofcrypto.example/realm",
    "http": "https://af-123.worldofcrypto.example",
    "capacity": 2000,
    "status": "high"
  },
  {
    "id": 124,
    "name": "Direhaven-05",
    "region": "af",
    "regionLabel": "Africa — Johannesburg",
    "flag": "🇿🇦",
    "timezone": "Africa/Johannesburg",
    "type": "Hardcore",
    "ws": "wss://af-124.worldofcrypto.example/realm",
    "http": "https://af-124.worldofcrypto.example",
    "capacity": 2000,
    "status": "full"
  }
];

const REALM_REGIONS = [
  {
    "code": "us-east",
    "label": "Americas — US East",
    "flag": "🇺🇸",
    "tz": "America/New_York"
  },
  {
    "code": "us-west",
    "label": "Americas — US West",
    "flag": "🇺🇸",
    "tz": "America/Los_Angeles"
  },
  {
    "code": "sa",
    "label": "South America — São Paulo",
    "flag": "🇧🇷",
    "tz": "America/Sao_Paulo"
  },
  {
    "code": "eu-central",
    "label": "Europe — Central",
    "flag": "🇪🇺",
    "tz": "Europe/Frankfurt"
  },
  {
    "code": "eu-west",
    "label": "Europe — West",
    "flag": "🇬🇧",
    "tz": "Europe/London"
  },
  {
    "code": "eu-nordic",
    "label": "Europe — Nordic",
    "flag": "🇸🇪",
    "tz": "Europe/Stockholm"
  },
  {
    "code": "me",
    "label": "Middle East — Dubai",
    "flag": "🇦🇪",
    "tz": "Asia/Dubai"
  },
  {
    "code": "ap-south",
    "label": "Asia Pacific — Mumbai",
    "flag": "🇮🇳",
    "tz": "Asia/Kolkata"
  },
  {
    "code": "ap-southeast",
    "label": "Asia Pacific — Singapore",
    "flag": "🇸🇬",
    "tz": "Asia/Singapore"
  },
  {
    "code": "ap-northeast",
    "label": "Asia Pacific — Tokyo",
    "flag": "🇯🇵",
    "tz": "Asia/Tokyo"
  },
  {
    "code": "kr",
    "label": "Asia Pacific — Seoul",
    "flag": "🇰🇷",
    "tz": "Asia/Seoul"
  },
  {
    "code": "oce",
    "label": "Oceania — Sydney",
    "flag": "🇦🇺",
    "tz": "Australia/Sydney"
  },
  {
    "code": "af",
    "label": "Africa — Johannesburg",
    "flag": "🇿🇦",
    "tz": "Africa/Johannesburg"
  }
];

/** Realms grouped by region code. */
function realmsByRegion(code) {
  return REALMS.filter((r) => r.region === code);
}

/** The total online population capacity across every realm. */
function totalCapacity() {
  return REALMS.reduce((sum, r) => sum + r.capacity, 0);
}

const DEFAULT_REALM = REALMS[0].id;

module.exports = { REALMS, REALM_REGIONS, realmsByRegion, totalCapacity, DEFAULT_REALM };
